
// Generated by dojo-bindgen on Fri, 4 Oct 2024 13:23:58 +0000. Do not modify this file manually.
// Import the necessary types from the recs SDK
// generate again with `sozo build --typescript` 
import { Account, byteArray } from "starknet";
import { DojoProvider } from "@dojoengine/core";
import * as models from "./models.gen";

export type IWorld = Awaited<ReturnType<typeof setupWorld>>;

export interface Signup {
    account: Account;
    name: string;
}

export interface Conquest {
    account: Account;
}

export interface Verify {
    account: Account;
    quest: number;
}

export async function setupWorld(provider: DojoProvider) {
    // System definitions for `conquest-Actions` contract
    function Actions() {
        const contract_name = "Actions";

        
        // Call the `world` system with the specified Account and calldata
        const world = async (props: { account: Account }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "world",
                        calldata: [],
                    },
                    "conquest"
                );
            } catch (error) {
                console.error("Error executing world:", error);
                throw error;
            }
        };
            

    
        // Call the `name` system with the specified Account and calldata
        const name = async (props: { account: Account }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "name",
                        calldata: [],
                    },
                    "conquest"
                );
            } catch (error) {
                console.error("Error executing name:", error);
                throw error;
            }
        };
            

    
        // Call the `signup` system with the specified Account and calldata
        const signup = async (props: { account: Account, name: string }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "signup",
                        calldata: [props.name],
                    },
                    "conquest"
                );
            } catch (error) {
                console.error("Error executing signup:", error);
                throw error;
            }
        };
            

    
        // Call the `conquest` system with the specified Account and calldata
        const conquest = async (props: { account: Account }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "conquest",
                        calldata: [],
                    },
                    "conquest"
                );
            } catch (error) {
                console.error("Error executing conquest:", error);
                throw error;
            }
        };
            

    
        // Call the `verify` system with the specified Account and calldata
        const verify = async (props: { account: Account, quest: number }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "verify",
                        calldata: [props.quest],
                    },
                    "conquest"
                );
            } catch (error) {
                console.error("Error executing verify:", error);
                throw error;
            }
        };
            

        return {
            world, name, signup, conquest, verify
        };
    }

    return {
        Actions: Actions()
    };
}
