
// Generated by dojo-bindgen on Fri, 25 Oct 2024 19:25:23 +0000. Do not modify this file manually.
// Import the necessary types from the recs SDK
// generate again with `sozo build --typescript` 
import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export type ContractComponents = Awaited<ReturnType<typeof defineContractComponents>>;

// Type definition for `conquest::models::index::Player` struct
export interface Player {
    id: BigInt;
    name: BigInt;
    
}
export const PlayerDefinition = {
    id: RecsType.BigInt,
    name: RecsType.BigInt,
    
};


// Type definition for `conquest::models::index::Tile` struct
export interface Tile {
    id: Number;
    player_id: BigInt;
    time: Number;
    
}
export const TileDefinition = {
    id: RecsType.Number,
    player_id: RecsType.BigInt,
    time: RecsType.Number,
    
};


export function defineContractComponents(world: World) {
    return {

        // Model definition for `conquest::models::index::Player` model
        Player: (() => {
            return defineComponent(
                world,
                {
                    id: RecsType.BigInt,
                    name: RecsType.BigInt,
                },
                {
                    metadata: {
                        namespace: "conquest",
                        name: "Player",
                        types: ["felt252", "felt252"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `conquest::models::index::Tile` model
        Tile: (() => {
            return defineComponent(
                world,
                {
                    id: RecsType.Number,
                    player_id: RecsType.BigInt,
                    time: RecsType.Number,
                },
                {
                    metadata: {
                        namespace: "conquest",
                        name: "Tile",
                        types: ["u32", "felt252", "u64"],
                        customTypes: [],
                    },
                }
            );
        })(),
    };
}
