
// Generated by dojo-bindgen on Fri, 25 Oct 2024 19:25:23 +0000. Do not modify this file manually.
// Import the necessary types from the recs SDK
// generate again with `sozo build --typescript` 
import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export type ContractComponents = Awaited<ReturnType<typeof defineContractComponents>>;



// Type definition for `dojo::model::layout::Layout` enum
export type Layout = { type: 'Fixed'; value: RecsType.NumberArray; } | { type: 'Struct'; value: RecsType.StringArray; } | { type: 'Tuple'; value: RecsType.StringArray; } | { type: 'Array'; value: RecsType.StringArray; } | { type: 'ByteArray'; } | { type: 'Enum'; value: RecsType.StringArray; };

export const LayoutDefinition = {
    type: RecsType.String,
    value: RecsType.String
};
        
// Type definition for `achievement::models::index::Achievement` struct
export interface Achievement {
    world_address: BigInt;
    namespace: BigInt;
    id: BigInt;
    published: Boolean;
    whitelisted: Boolean;
    karma: Number;
    
}
export const AchievementDefinition = {
    world_address: RecsType.BigInt,
    namespace: RecsType.BigInt,
    id: RecsType.BigInt,
    published: RecsType.Boolean,
    whitelisted: RecsType.Boolean,
    karma: RecsType.Number,
    
};

// Type definition for `core::byte_array::ByteArray` struct
export interface ByteArray {
    data: String[];
    pending_word: BigInt;
    pending_word_len: Number;
    
}
export const ByteArrayDefinition = {
    data: RecsType.StringArray,
    pending_word: RecsType.BigInt,
    pending_word_len: RecsType.Number,
    
};

// Type definition for `dojo::model::layout::FieldLayout` struct
export interface FieldLayout {
    selector: BigInt;
    layout: Layout;
    
}
export const FieldLayoutDefinition = {
    selector: RecsType.BigInt,
    layout: LayoutDefinition,
    
};


// Type definition for `achievement::events::index::AchievementCompletion` struct
export interface AchievementCompletion {
    player_id: BigInt;
    quest: BigInt;
    count: Number;
    time: Number;
    
}
export const AchievementCompletionDefinition = {
    player_id: RecsType.BigInt,
    quest: RecsType.BigInt,
    count: RecsType.Number,
    time: RecsType.Number,
    
};


// Type definition for `achievement::events::index::AchievementCreation` struct
export interface AchievementCreation {
    identifier: BigInt;
    quest: BigInt;
    hidden: Boolean;
    points: Number;
    total: Number;
    title: BigInt;
    description: String;
    icon: BigInt;
    time: Number;
    
}
export const AchievementCreationDefinition = {
    identifier: RecsType.BigInt,
    quest: RecsType.BigInt,
    hidden: RecsType.Boolean,
    points: RecsType.Number,
    total: RecsType.Number,
    title: RecsType.BigInt,
    description: RecsType.String,
    icon: RecsType.BigInt,
    time: RecsType.Number,
    
};


// Type definition for `achievement::models::index::Game` struct
export interface Game {
    world_address: BigInt;
    namespace: BigInt;
    published: Boolean;
    whitelisted: Boolean;
    total_karma: Number;
    name: String;
    description: String;
    torii_url: String;
    image_uri: String;
    owner: BigInt;
    
}
export const GameDefinition = {
    world_address: RecsType.BigInt,
    namespace: RecsType.BigInt,
    published: RecsType.Boolean,
    whitelisted: RecsType.Boolean,
    total_karma: RecsType.Number,
    name: RecsType.String,
    description: RecsType.String,
    torii_url: RecsType.String,
    image_uri: RecsType.String,
    owner: RecsType.BigInt,
    
};


// Type definition for `conquest::models::index::Player` struct
export interface Player {
    id: BigInt;
    name: BigInt;
    
}
export const PlayerDefinition = {
    id: RecsType.BigInt,
    name: RecsType.BigInt,
    
};


// Type definition for `conquest::models::index::Tile` struct
export interface Tile {
    id: Number;
    player_id: BigInt;
    time: Number;
    
}
export const TileDefinition = {
    id: RecsType.Number,
    player_id: RecsType.BigInt,
    time: RecsType.Number,
    
};


export function defineContractComponents(world: World) {
    return {

        // Model definition for `achievement::models::index::Achievement` model
        Achievement: (() => {
            return defineComponent(
                world,
                {
                    world_address: RecsType.BigInt,
                    namespace: RecsType.BigInt,
                    id: RecsType.BigInt,
                    published: RecsType.Boolean,
                    whitelisted: RecsType.Boolean,
                    karma: RecsType.Number,
                },
                {
                    metadata: {
                        namespace: "conquest",
                        name: "Achievement",
                        types: ["felt252", "felt252", "felt252", "bool", "bool", "u16"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `achievement::events::index::AchievementCompletion` model
        AchievementCompletion: (() => {
            return defineComponent(
                world,
                {
                    player_id: RecsType.BigInt,
                    quest: RecsType.BigInt,
                    count: RecsType.Number,
                    time: RecsType.Number,
                },
                {
                    metadata: {
                        namespace: "conquest",
                        name: "AchievementCompletion",
                        types: ["felt252", "felt252", "u32", "u64"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `achievement::events::index::AchievementCreation` model
        AchievementCreation: (() => {
            return defineComponent(
                world,
                {
                    identifier: RecsType.BigInt,
                    quest: RecsType.BigInt,
                    hidden: RecsType.Boolean,
                    points: RecsType.Number,
                    total: RecsType.Number,
                    title: RecsType.BigInt,
                    description: RecsType.String,
                    icon: RecsType.BigInt,
                    time: RecsType.Number,
                },
                {
                    metadata: {
                        namespace: "conquest",
                        name: "AchievementCreation",
                        types: ["felt252", "felt252", "bool", "u16", "u32", "felt252", "felt252", "u64"],
                        customTypes: ["ByteArray"],
                    },
                }
            );
        })(),

        // Model definition for `achievement::models::index::Game` model
        Game: (() => {
            return defineComponent(
                world,
                {
                    world_address: RecsType.BigInt,
                    namespace: RecsType.BigInt,
                    published: RecsType.Boolean,
                    whitelisted: RecsType.Boolean,
                    total_karma: RecsType.Number,
                    name: RecsType.String,
                    description: RecsType.String,
                    torii_url: RecsType.String,
                    image_uri: RecsType.String,
                    owner: RecsType.BigInt,
                },
                {
                    metadata: {
                        namespace: "conquest",
                        name: "Game",
                        types: ["felt252", "felt252", "bool", "bool", "u16", "felt252"],
                        customTypes: ["ByteArray", "ByteArray", "ByteArray", "ByteArray"],
                    },
                }
            );
        })(),

        // Model definition for `conquest::models::index::Player` model
        Player: (() => {
            return defineComponent(
                world,
                {
                    id: RecsType.BigInt,
                    name: RecsType.BigInt,
                },
                {
                    metadata: {
                        namespace: "conquest",
                        name: "Player",
                        types: ["felt252", "felt252"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `conquest::models::index::Tile` model
        Tile: (() => {
            return defineComponent(
                world,
                {
                    id: RecsType.Number,
                    player_id: RecsType.BigInt,
                    time: RecsType.Number,
                },
                {
                    metadata: {
                        namespace: "conquest",
                        name: "Tile",
                        types: ["u32", "felt252", "u64"],
                        customTypes: [],
                    },
                }
            );
        })(),
    };
}
