kind = "DojoModel"
class_hash = "0x12af05b982971ae1961eb175b5cd82d0f1dc416eddc3508066ad4671045cfd6"
original_class_hash = "0x12af05b982971ae1961eb175b5cd82d0f1dc416eddc3508066ad4671045cfd6"
abi = "manifests/dev/base/abis/models/conquest-AchievementCreation-4c815d24.json"
tag = "conquest-AchievementCreation"
qualified_path = "achievement::events::index::achievement_creation"
manifest_name = "conquest-AchievementCreation-4c815d24"

[[members]]
name = "identifier"
type = "felt252"
key = true

[[members]]
name = "quest"
type = "felt252"
key = false

[[members]]
name = "hidden"
type = "bool"
key = false

[[members]]
name = "points"
type = "u16"
key = false

[[members]]
name = "total"
type = "u32"
key = false

[[members]]
name = "title"
type = "felt252"
key = false

[[members]]
name = "description"
type = "ByteArray"
key = false

[[members]]
name = "icon"
type = "felt252"
key = false

[[members]]
name = "time"
type = "u64"
key = false
