[world]
name = "Conquest"
description = "Dojo Quests Example"
website = "https://github.com/dojoengine/dojo"
seed = "conquest"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "conquest"
mappings = { "achievement" = "conquest" }

[env]
rpc_url = "http://localhost:5051/"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
