kind = "DojoModel"
class_hash = "0x1bfc433e762613b252857889fe325939e4e8ee8ce451692de2c57a7b788edbd"
original_class_hash = "0x1bfc433e762613b252857889fe325939e4e8ee8ce451692de2c57a7b788edbd"
abi = "manifests/slot/base/abis/models/conquest-AchievementCompletion-1d044dbd.json"
tag = "conquest-AchievementCompletion"
qualified_path = "achievement::events::index::achievement_completion"
manifest_name = "conquest-AchievementCompletion-1d044dbd"

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "identifier"
type = "felt252"
key = true

[[members]]
name = "count"
type = "u32"
key = false

[[members]]
name = "time"
type = "u64"
key = false
